### ISSUE TITLE
Show more calculated values

### ISSUE THREAD

**Issue by tbrown** [modularscale/modularscale.com#64] opened 2015-03-09 15:49 UTC
Note from a user:

> Since it changed I found a problem though, I does not show enough font sizes. For example I need a font size close to 100px and it is only showing up to around 60px.  It would be awesome if there was an option to show more.

**Comment by scottkellum** [comment] 2015-03-09 15:52
Dupe of #55

**Closed by scottkellum** 2015-03-09 15:52 UTC
Labels: duplicate
